# 임의의 데이터로 확인하는 인덱스 중복 여부

In [ ]:
import pandas as pd
import numpy as np

series1 = pd.Series([4, 5, 6, 3, 1], name="Mango")
series2 = pd.Series([4, 5, 6, 3, 1], name="Mango")
series3 = pd.Series([2, 3, 5, 2, 7], name="Banana")

fruits1 = pd.concat([series1, series2, series3], axis=1)
fruits1

   Mango  Mango  Banana
0      4      4       2
1      5      5       3
2      6      6       5
3      3      3       2
4      1      1       7

In [ ]:
#컬럼 중복 확인
fruits1.columns.duplicated(keep=False)

array([ True,  True, False])

In [ ]:
#중복 컬럼 출력
dup_cols=fruits1.iloc[:,fruits1.columns.duplicated(keep=False)]
print(dup_cols)

   Mango  Mango
0      4      4
1      5      5
2      6      6
3      3      3
4      1      1

In [ ]:
#중복 컬럼(T 사용해 행렬 전치) 출력
fruits1.T.duplicated()

Mango     False
Mango      True
Banana    False
dtype: bool

In [ ]:
#중복 컬럼 삭제 후 확인
fruits1=fruits1.loc[:,~fruits1.T.duplicated()]
fruits1

   Mango  Banana
0      4       2
1      5       3
2      6       5
3      3       2
4      1       7

# housing.csv의 중복 여부

In [ ]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

In [ ]:
housing = pd.read_csv(data_url+'housing.csv')

In [ ]:
#중복값 존재하지 않아 강제 생성
housing['total_rooms_dup'] = housing['total_rooms']
housing['total_rooms_dup2']=housing['latitude']
housing.rename(columns={'total_rooms_dup': 'total_rooms'}, inplace=True)
housing.rename(columns={'total_rooms_dup2': 'total_rooms'}, inplace=True)

In [ ]:
#중복 컬럼 생성 확인
print(housing.loc[:,'total_rooms'])

       total_rooms  total_rooms  total_rooms
0            880.0        880.0        37.88
1           7099.0       7099.0        37.86
2           1467.0       1467.0        37.85
3           1274.0       1274.0        37.85
4           1627.0       1627.0        37.85
...            ...          ...          ...
20635       1665.0       1665.0        39.48
20636        697.0        697.0        39.49
20637       2254.0       2254.0        39.43
20638       1860.0       1860.0        39.43
20639       2785.0       2785.0        39.37

[20640 rows x 3 columns]

In [ ]:
#원본 데이터 확인
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,total_rooms,total_rooms
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,880.0,37.88
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,7099.0,37.86
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,1467.0,37.85
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,1274.0,37.85
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,1627.0,37.85
...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,1665.0,39.48
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,697.0,39.49
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,2254.0,39.43
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,1860.0,39.43
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,2785.0,39.37

In [ ]:
#열 기준 중복 데이터값 기준 삭제
housing_boolarr=housing.T.duplicated()
housing=housing.loc[:, ~housing_boolarr]
housing

#행기준 중복 데이터 값 삭제
# housing=housing.drop_duplicates()
# housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [ ]:
#중복 인덱스 기준 삭제
housing_boolarr=housing.columns.duplicated()
housing=housing.loc[:,~housing_boolarr]
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [ ]:
#중복 값과 인덱스 기준 삭제
housing_boolarr=housing.T.duplicated()&housing.columns.duplicated()
housing=housing.loc[:,~housing_boolarr]
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [ ]:
boolean=housing.columns.duplicated()

In [ ]:
housing.columns.values[boolean] = 'check'

In [ ]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,check,check
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,880.0,37.88
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,7099.0,37.86
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,1467.0,37.85
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,1274.0,37.85
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,1627.0,37.85
...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,1665.0,39.48
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,697.0,39.49
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,2254.0,39.43
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,1860.0,39.43
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,2785.0,39.37

In [ ]:
cols = pd.Series(housing.columns)
print(cols[cols.duplicated()])
for dup in cols[cols.duplicated()].unique():
  print("중복 데이터",dup)
  Idx=cols[cols==dup].index
  print("인덱스",Idx)
  new_cols = []

  for i in range(len(Idx)):
      if i == 0:
          new_cols.append(dup)          # 첫 번째는 그대로
          print("중복컬럼 0",new_cols[i])
      else:
          new_cols.append(f"{dup}_{i}") # 나머지는 번호 붙임
          print("중복컬럼",i,new_cols[i])

  cols[Idx] = new_cols

housing.columns = cols
housing

10    total_rooms
11    total_rooms
dtype: object
중복 데이터 total_rooms
인덱스 Index([3, 10, 11], dtype='int64')
중복컬럼 0 total_rooms
중복컬럼 1 total_rooms_1
중복컬럼 2 total_rooms_2

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,total_rooms_1,total_rooms_2
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,880.0,37.88
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,7099.0,37.86
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,1467.0,37.85
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,1274.0,37.85
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,1627.0,37.85
...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,1665.0,39.48
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,697.0,39.49
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND,2254.0,39.43
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,1860.0,39.43
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,2785.0,39.37

In [ ]:
print(f"인덱스 중복 없는가? : {housing.columns.is_unique}")

인덱스 중복 없는가? : True

# 임의의 시리즈를 활용한 인덱스 중복 여부

In [ ]:
series1 = pd.Series([4, 5, 3, 3, 1], index=['a','b','a','c','d'])
series1

a    4
b    5
a    3
c    3
d    1
dtype: int64

In [ ]:
#중복 인덱스 확인
series1.index.duplicated(keep=False)

array([ True, False,  True, False, False])

In [ ]:
#중복 데이터 확인
series1.duplicated()

a    False
b    False
a    False
c     True
d    False
dtype: bool