In [2]:
import numpy as np
import pandas as pd

data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

pd.set_option('display.precision',6)

In [4]:
two_days=pd.date_range(start="20260301", periods=48, freq="h")
two_days

DatetimeIndex(['2026-03-01 00:00:00', '2026-03-01 01:00:00',
               '2026-03-01 02:00:00', '2026-03-01 03:00:00',
               '2026-03-01 04:00:00', '2026-03-01 05:00:00',
               '2026-03-01 06:00:00', '2026-03-01 07:00:00',
               '2026-03-01 08:00:00', '2026-03-01 09:00:00',
               '2026-03-01 10:00:00', '2026-03-01 11:00:00',
               '2026-03-01 12:00:00', '2026-03-01 13:00:00',
               '2026-03-01 14:00:00', '2026-03-01 15:00:00',
               '2026-03-01 16:00:00', '2026-03-01 17:00:00',
               '2026-03-01 18:00:00', '2026-03-01 19:00:00',
               '2026-03-01 20:00:00', '2026-03-01 21:00:00',
               '2026-03-01 22:00:00', '2026-03-01 23:00:00',
               '2026-03-02 00:00:00', '2026-03-02 01:00:00',
               '2026-03-02 02:00:00', '2026-03-02 03:00:00',
               '2026-03-02 04:00:00', '2026-03-02 05:00:00',
               '2026-03-02 06:00:00', '2026-03-02 07:00:00',
               '2026-03-02 08:00:00', '2026-03-02 09:00:00',
               '2026-03-02 10:00:00', '2026-03-02 11:00:00',
               '2026-03-02 12:00:00', '2026-03-02 13:00:00',
               '2026-03-02 14:00:00', '2026-03-02 15:00:00',
               '2026-03-02 16:00:00', '2026-03-02 17:00:00',
               '2026-03-02 18:00:00', '2026-03-02 19:00:00',
               '2026-03-02 20:00:00', '2026-03-02 21:00:00',
               '2026-03-02 22:00:00', '2026-03-02 23:00:00'],
              dtype='datetime64[us]', freq='h')

In [5]:
two_days[0]
two_days[24]

Timestamp('2026-03-02 00:00:00')

In [6]:
two_days[[0,24]]

DatetimeIndex(['2026-03-01', '2026-03-02'], dtype='datetime64[us]', freq=None)

In [8]:
two_days[24:36]

DatetimeIndex(['2026-03-02 00:00:00', '2026-03-02 01:00:00',
               '2026-03-02 02:00:00', '2026-03-02 03:00:00',
               '2026-03-02 04:00:00', '2026-03-02 05:00:00',
               '2026-03-02 06:00:00', '2026-03-02 07:00:00',
               '2026-03-02 08:00:00', '2026-03-02 09:00:00',
               '2026-03-02 10:00:00', '2026-03-02 11:00:00'],
              dtype='datetime64[us]', freq='h')

In [11]:
one_day=pd.date_range(start="20260401", periods=24, freq="h")

In [12]:
one_day

DatetimeIndex(['2026-04-01 00:00:00', '2026-04-01 01:00:00',
               '2026-04-01 02:00:00', '2026-04-01 03:00:00',
               '2026-04-01 04:00:00', '2026-04-01 05:00:00',
               '2026-04-01 06:00:00', '2026-04-01 07:00:00',
               '2026-04-01 08:00:00', '2026-04-01 09:00:00',
               '2026-04-01 10:00:00', '2026-04-01 11:00:00',
               '2026-04-01 12:00:00', '2026-04-01 13:00:00',
               '2026-04-01 14:00:00', '2026-04-01 15:00:00',
               '2026-04-01 16:00:00', '2026-04-01 17:00:00',
               '2026-04-01 18:00:00', '2026-04-01 19:00:00',
               '2026-04-01 20:00:00', '2026-04-01 21:00:00',
               '2026-04-01 22:00:00', '2026-04-01 23:00:00'],
              dtype='datetime64[us]', freq='h')

In [13]:
weather_df=pd.DataFrame(np.arange(48).reshape(2,24),
                        index=['온도','습도'],
                        columns=one_day)
weather_df

,2026-04-01 00:00:00,2026-04-01 01:00:00,2026-04-01 02:00:00,2026-04-01 03:00:00,2026-04-01 04:00:00,2026-04-01 05:00:00,2026-04-01 06:00:00,2026-04-01 07:00:00,2026-04-01 08:00:00,2026-04-01 09:00:00,...,2026-04-01 14:00:00,2026-04-01 15:00:00,2026-04-01 16:00:00,2026-04-01 17:00:00,2026-04-01 18:00:00,2026-04-01 19:00:00,2026-04-01 20:00:00,2026-04-01 21:00:00,2026-04-01 22:00:00,2026-04-01 23:00:00
온도,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
습도,24,25,26,27,28,29,30,31,32,33,...,38,39,40,41,42,43,44,45,46,47

In [15]:
weather_df=pd.DataFrame(np.arange(48).reshape(24,2),
                        index=one_day,
                        columns=['온도','습도'])

weather_df

                     온도  습도
2026-04-01 00:00:00   0   1
2026-04-01 01:00:00   2   3
2026-04-01 02:00:00   4   5
2026-04-01 03:00:00   6   7
2026-04-01 04:00:00   8   9
2026-04-01 05:00:00  10  11
2026-04-01 06:00:00  12  13
2026-04-01 07:00:00  14  15
2026-04-01 08:00:00  16  17
2026-04-01 09:00:00  18  19
2026-04-01 10:00:00  20  21
2026-04-01 11:00:00  22  23
2026-04-01 12:00:00  24  25
2026-04-01 13:00:00  26  27
2026-04-01 14:00:00  28  29
2026-04-01 15:00:00  30  31
2026-04-01 16:00:00  32  33
2026-04-01 17:00:00  34  35
2026-04-01 18:00:00  36  37
2026-04-01 19:00:00  38  39
2026-04-01 20:00:00  40  41
2026-04-01 21:00:00  42  43
2026-04-01 22:00:00  44  45
2026-04-01 23:00:00  46  47

In [16]:
sons_df=pd.read_csv(data_url+"pearson_dataset.csv", header=0, usecols=[1])
sons_df

        Son
0     151.9
1     160.5
2     160.8
3     159.5
4     163.3
...     ...
1073  179.8
1074  173.5
1075  176.0
1076  176.0
1077  170.2

[1078 rows x 1 columns]

In [17]:
pearson_df = pd.read_csv(data_url+"pearson_dataset.csv", header=0)
pearson_df

      Father    Son
0      165.1  151.9
1      160.8  160.5
2      165.1  160.8
3      167.1  159.5
4      155.2  163.3
...      ...    ...
1073   170.2  179.8
1074   181.1  173.5
1075   182.4  176.0
1076   179.6  176.0
1077   178.6  170.2

[1078 rows x 2 columns]

In [18]:
pearson_df.index

RangeIndex(start=0, stop=1078, step=1)

In [19]:
pearson_df.columns

Index(['Father', 'Son'], dtype='str')

In [20]:
pearson_df.shape

(1078, 2)

In [ ]:
pearson_df.dtypes
#pearson_df의 열별 자료형을 확인한다.

Father    float64
Son       float64
dtype: object

In [24]:
pearson_df.values
#행과 열 인덱스를 제외한 항목만으로 구성된 넘파이 2차원 어레이를 가리킨다.

array([[165.1, 151.9],
       [160.8, 160.5],
       [165.1, 160.8],
       ...,
       [182.4, 176. ],
       [179.6, 176. ],
       [178.6, 170.2]], shape=(1078, 2))

In [25]:
iris_df=pd.read_csv(data_url+"iris.csv", header=0)
iris_df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [26]:
iris_df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety             str
dtype: object

In [27]:
iris_df.shape

(150, 5)

In [28]:
iris_df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='str')

In [29]:
iris_df.values[:10]

array([[5.1, 3.5, 1.4, 0.2, 'Setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Setosa']], dtype=object)

In [30]:
iris_df.values.dtype

dtype('O')

In [31]:
dates=pd.date_range(start="20260301", periods=6, freq="D")
df=pd.DataFrame(np.arange(24).reshape(6,4), index=dates, columns=list("ABCD"))
df

             A   B   C   D
2026-03-01   0   1   2   3
2026-03-02   4   5   6   7
2026-03-03   8   9  10  11
2026-03-04  12  13  14  15
2026-03-05  16  17  18  19
2026-03-06  20  21  22  23

In [34]:
df["A"]

2026-03-01     0
2026-03-02     4
2026-03-03     8
2026-03-04    12
2026-03-05    16
2026-03-06    20
Freq: D, Name: A, dtype: int64

In [37]:
df.iloc[:,0]

2026-03-01     0
2026-03-02     4
2026-03-03     8
2026-03-04    12
2026-03-05    16
2026-03-06    20
Freq: D, Name: A, dtype: int64

In [38]:
df.loc[:,'A']

2026-03-01     0
2026-03-02     4
2026-03-03     8
2026-03-04    12
2026-03-05    16
2026-03-06    20
Freq: D, Name: A, dtype: int64

In [39]:
df.A

2026-03-01     0
2026-03-02     4
2026-03-03     8
2026-03-04    12
2026-03-05    16
2026-03-06    20
Freq: D, Name: A, dtype: int64

In [41]:
df.loc[dates[0]]

A    0
B    1
C    2
D    3
Name: 2026-03-01 00:00:00, dtype: int64

In [42]:
df.loc[:,'A':'B']

             A   B
2026-03-01   0   1
2026-03-02   4   5
2026-03-03   8   9
2026-03-04  12  13
2026-03-05  16  17
2026-03-06  20  21

In [43]:
df.loc[:,['A','B']]

             A   B
2026-03-01   0   1
2026-03-02   4   5
2026-03-03   8   9
2026-03-04  12  13
2026-03-05  16  17
2026-03-06  20  21

In [44]:
df.iloc[3]

A    12
B    13
C    14
D    15
Name: 2026-03-04 00:00:00, dtype: int64

In [45]:
df.loc[['2026-03-01', '2026-03-03', '2026-03-06']]

             A   B   C   D
2026-03-01   0   1   2   3
2026-03-03   8   9  10  11
2026-03-06  20  21  22  23

In [46]:
df.iloc[1::2, :]

             A   B   C   D
2026-03-02   4   5   6   7
2026-03-04  12  13  14  15
2026-03-06  20  21  22  23

In [47]:
df.iloc[:,[1,2]]

             B   C
2026-03-01   1   2
2026-03-02   5   6
2026-03-03   9  10
2026-03-04  13  14
2026-03-05  17  18
2026-03-06  21  22

In [48]:
iris_df = pd.read_csv(data_url+"iris.csv")
iris_df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [50]:
iris_df.iloc[:,-1]

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: str

In [51]:
iris_df.loc[:,'variety']

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: str

In [52]:
iris_df.iloc[0].squeeze()

sepal.length       5.1
sepal.width        3.5
petal.length       1.4
petal.width        0.2
variety         Setosa
Name: 0, dtype: object

In [53]:
iris_df.loc[:, ['sepal.length', 'petal.length']]

     sepal.length  petal.length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

In [55]:
iris_df.iloc[[0,50,100]]

     sepal.length  sepal.width  petal.length  petal.width     variety
0             5.1          3.5           1.4          0.2      Setosa
50            7.0          3.2           4.7          1.4  Versicolor
100           6.3          3.3           6.0          2.5   Virginica

In [57]:
sample_df = pd.DataFrame({"X": range(10), "Y": range(10, 20)})
sample_df

   X   Y
0  0  10
1  1  11
2  2  12
3  3  13
4  4  14
5  5  15
6  6  16
7  7  17
8  8  18
9  9  19

In [58]:
sample_df.iloc[3]

X     3
Y    13
Name: 3, dtype: int64

In [59]:
sample_df.loc[3]

X     3
Y    13
Name: 3, dtype: int64