In [1]:
import numpy as np
import pandas as pd

In [2]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

In [11]:
series1 = pd.Series([4, 5, 6, 3, 1], name="Mango")
series2 = pd.Series([5, 4, 3, 0, 2], name="Apple")
series3 = pd.Series([2, 3, 5, 2, 7], name="Banana")

fruits1 = pd.concat([series1, series2, series3], axis=1)
fruits1

   Mango  Apple  Banana
0      4      5       2
1      5      4       3
2      6      3       5
3      3      0       2
4      1      2       7

In [4]:
type(fruits1)

pandas.core.frame.DataFrame

In [5]:
fruits1.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
fruits_array=np.array([[4,5,2],
                       [5,4,3],
                       [6,3,5],
                       [3,0,2],
                       [1,2,7]])

In [7]:
fruits1=pd.DataFrame(fruits_array,
                     columns=['Mango','Apple','Banana'])
fruits1

   Mango  Apple  Banana
0      4      5       2
1      5      4       3
2      6      3       5
3      3      0       2
4      1      2       7

In [12]:
fruits1.columns

Index(['Mango', 'Apple', 'Banana'], dtype='object')

In [17]:
fruits1=pd.DataFrame(fruits_array,
                     columns=['Mango','Apple','Banana'],
                     index=['A','B','C','D','E'])
fruits1

   Mango  Apple  Banana
A      4      5       2
B      5      4       3
C      6      3       5
D      3      0       2
E      1      2       7

In [19]:
fruits1.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [20]:
fruits_dict={'Mango':[4,5,6,3,1],
             'Apple':[5,4,3,0,2],
             'Banana':[2,3,5,2,7]}

fruits1=pd.DataFrame(fruits_dict)
fruits1

   Mango  Apple  Banana
0      4      5       2
1      5      4       3
2      6      3       5
3      3      0       2
4      1      2       7

In [21]:
fruits1.index

RangeIndex(start=0, stop=5, step=1)

In [22]:
pearson_df=pd.read_csv(data_url+"pearson_dataset.csv", header=0)
pearson_df

      Father    Son
0      165.1  151.9
1      160.8  160.5
2      165.1  160.8
3      167.1  159.5
4      155.2  163.3
...      ...    ...
1073   170.2  179.8
1074   181.1  173.5
1075   182.4  176.0
1076   179.6  176.0
1077   178.6  170.2

[1078 rows x 2 columns]

In [25]:
dates=pd.date_range(start="20260301",periods=5, freq="D")
dates

DatetimeIndex(['2026-03-01', '2026-03-02', '2026-03-03', '2026-03-04',
               '2026-03-05'],
              dtype='datetime64[ns]', freq='D')

In [29]:
fruits_date=pd.DataFrame(fruits_dict,index=dates)
fruits_date

            Mango  Apple  Banana
2026-03-01      4      5       2
2026-03-02      5      4       3
2026-03-03      6      3       5
2026-03-04      3      0       2
2026-03-05      1      2       7

In [78]:
two_days=pd.date_range(start="Jan 1, 2026", periods=48, freq="h")
two_days

DatetimeIndex(['2026-01-01 00:00:00', '2026-01-01 01:00:00',
               '2026-01-01 02:00:00', '2026-01-01 03:00:00',
               '2026-01-01 04:00:00', '2026-01-01 05:00:00',
               '2026-01-01 06:00:00', '2026-01-01 07:00:00',
               '2026-01-01 08:00:00', '2026-01-01 09:00:00',
               '2026-01-01 10:00:00', '2026-01-01 11:00:00',
               '2026-01-01 12:00:00', '2026-01-01 13:00:00',
               '2026-01-01 14:00:00', '2026-01-01 15:00:00',
               '2026-01-01 16:00:00', '2026-01-01 17:00:00',
               '2026-01-01 18:00:00', '2026-01-01 19:00:00',
               '2026-01-01 20:00:00', '2026-01-01 21:00:00',
               '2026-01-01 22:00:00', '2026-01-01 23:00:00',
               '2026-01-02 00:00:00', '2026-01-02 01:00:00',
               '2026-01-02 02:00:00', '2026-01-02 03:00:00',
               '2026-01-02 04:00:00', '2026-01-02 05:00:00',
               '2026-01-02 06:00:00', '2026-01-02 07:00:00',
               '2026-01-02 08:00:00', '2026-01-02 09:00:00',
               '2026-01-02 10:00:00', '2026-01-02 11:00:00',
               '2026-01-02 12:00:00', '2026-01-02 13:00:00',
               '2026-01-02 14:00:00', '2026-01-02 15:00:00',
               '2026-01-02 16:00:00', '2026-01-02 17:00:00',
               '2026-01-02 18:00:00', '2026-01-02 19:00:00',
               '2026-01-02 20:00:00', '2026-01-02 21:00:00',
               '2026-01-02 22:00:00', '2026-01-02 23:00:00'],
              dtype='datetime64[ns]', freq='h')

In [79]:
start = two_days.get_loc("2026-01-02 00:00")
end = two_days.get_loc("2026-01-02 11:00")

two_days[start:end+1]

DatetimeIndex(['2026-01-02 00:00:00', '2026-01-02 01:00:00',
               '2026-01-02 02:00:00', '2026-01-02 03:00:00',
               '2026-01-02 04:00:00', '2026-01-02 05:00:00',
               '2026-01-02 06:00:00', '2026-01-02 07:00:00',
               '2026-01-02 08:00:00', '2026-01-02 09:00:00',
               '2026-01-02 10:00:00', '2026-01-02 11:00:00'],
              dtype='datetime64[ns]', freq='h')

In [40]:
two_days[0]

Timestamp('2026-03-01 00:00:00')

In [41]:
two_days[24]

Timestamp('2026-03-02 00:00:00')

In [44]:
two_days[[0,24]]

DatetimeIndex(['2026-01-01', '2026-01-02'], dtype='datetime64[ns]', freq=None)

In [45]:
two_days[24:36]

DatetimeIndex(['2026-01-02 00:00:00', '2026-01-02 01:00:00',
               '2026-01-02 02:00:00', '2026-01-02 03:00:00',
               '2026-01-02 04:00:00', '2026-01-02 05:00:00',
               '2026-01-02 06:00:00', '2026-01-02 07:00:00',
               '2026-01-02 08:00:00', '2026-01-02 09:00:00',
               '2026-01-02 10:00:00', '2026-01-02 11:00:00'],
              dtype='datetime64[ns]', freq='h')

In [82]:
two_days["2026-03-02":"2026-03-02 11:00"]

TypeError: slice indices must be integers or None or have an __index__ method

In [76]:
two_days['2026-03-02 00:00:00':'2026-03-02 11:00:00']

TypeError: slice indices must be integers or None or have an __index__ method

In [50]:
import pandas as pd

# 예시 DatetimeIndex
two_days = pd.date_range('2026-03-01 00:00:00', '2026-03-02 23:00:00', freq='H')

# 원하는 범위
start = pd.Timestamp('2026-03-02 00:00:00')
end   = pd.Timestamp('2026-03-02 11:00:00')

# for문으로 필터링
selected = [t for t in two_days if start <= t <= end]
print(pd.DatetimeIndex(selected))

DatetimeIndex(['2026-03-02 00:00:00', '2026-03-02 01:00:00',
               '2026-03-02 02:00:00', '2026-03-02 03:00:00',
               '2026-03-02 04:00:00', '2026-03-02 05:00:00',
               '2026-03-02 06:00:00', '2026-03-02 07:00:00',
               '2026-03-02 08:00:00', '2026-03-02 09:00:00',
               '2026-03-02 10:00:00', '2026-03-02 11:00:00'],
              dtype='datetime64[ns]', freq=None)

C:\Users\skato\AppData\Local\Temp\ipykernel_28016\3658120185.py:4: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  two_days = pd.date_range('2026-03-01 00:00:00', '2026-03-02 23:00:00', freq='H')

In [74]:
start = pd.Timestamp('2026-03-02 00:00:00')
end   = pd.Timestamp('2026-03-02 11:00:00')

selected=[]

for t in two_days:
    if start<=t and t<=end:
        selected.append(t)

selected=pd.DatetimeIndex(selected)
type(selected)

pandas.core.indexes.datetimes.DatetimeIndex

In [72]:
df = pd.DataFrame(index=two_days)
type(df)
# df.loc['2026-03-02 00:00:00':'2026-03-02 11:00:00']

pandas.core.frame.DataFrame

In [63]:
result = two_days["2026-03-02 00:00":"2026-03-02 11:00"]

TypeError: slice indices must be integers or None or have an __index__ method

In [89]:
fathers_array = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1, usecols=0)
fathers = pd.Series(fathers_array, name="Father")
fathers

0       165.1
1       160.8
2       165.1
3       167.1
4       155.2
        ...
1073    170.2
1074    181.1
1075    182.4
1076    179.6
1077    178.6
Name: Father, Length: 1078, dtype: float64

In [90]:
type(fathers)
fathers.ndim

1

In [84]:
fathers = pd.read_csv(data_url+"pearson_dataset.csv", usecols=[0]).squeeze()
fathers

0       165.1
1       160.8
2       165.1
3       167.1
4       155.2
        ...
1073    170.2
1074    181.1
1075    182.4
1076    179.6
1077    178.6
Name: Father, Length: 1078, dtype: float64

In [85]:
type(fathers)

pandas.core.series.Series

In [88]:
fathers.ndim

1

In [95]:
fathers=pd.read_csv(data_url+"pearson_dataset.csv", usecols=[0])

In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.Series(range(5),index=list('abcde'), dtype="float32")

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float32

In [4]:

abcd_dict = {"A": 1.0,
             "B": pd.Series(range(5), dtype="float32"),
             "C": np.array([3] * 5, dtype="int32"),
             "D": ["test", "train", "test", "train", "test"],}

In [7]:
abcd_df=pd.DataFrame(abcd_dict)
abcd_df

     A    B  C      D
0  1.0  0.0  3   test
1  1.0  1.0  3  train
2  1.0  2.0  3   test
3  1.0  3.0  3  train
4  1.0  4.0  3   test

In [ ]:
abcd_df.dtypes
#object 모든 타입들의 시조야

A    float64
B    float32
C      int32
D     object
dtype: object

In [9]:
fruits_array = np.array([[4, 5, 2],
                         [5, 4, 3],
                         [6, 3, 5],
                         [3, 0, 2],
                         [1, 2, 7]])

fruits3 = pd.DataFrame(fruits_array,
                       columns=['Mango', 'Apple', 'Banana'],
                       index=['A', 'B', 'C', 'D', 'E'])

fruits3

   Mango  Apple  Banana
A      4      5       2
B      5      4       3
C      6      3       5
D      3      0       2
E      1      2       7

In [11]:
fruits3['Mango']

A    4
B    5
C    6
D    3
E    1
Name: Mango, dtype: int32

In [12]:
fruits3.Banana

A    2
B    3
C    5
D    2
E    7
Name: Banana, dtype: int32

In [28]:
fruits3.loc['C':,'Apple'] #문자열로 인덱싱 가능

C    3
D    0
E    2
Name: Apple, dtype: int32

In [ ]:
fruits3.iloc[2:,1] #정수 인덱스로 인덱싱 적용

C    3
D    0
E    2
Name: Apple, dtype: int32

In [20]:
fruits3['Passion fruit']=7
fruits3

   Mango  Apple  Banana  Passion fruit
A      4      5       2              7
B      5      4       3              7
C      6      3       5              7
D      3      0       2              7
E      1      2       7              7

In [21]:
fruits3['Passion fruit']=5
fruits3

   Mango  Apple  Banana  Passion fruit
A      4      5       2              5
B      5      4       3              5
C      6      3       5              5
D      3      0       2              5
E      1      2       7              5

In [22]:
fruits3['Grape']=range(10,15)
fruits3

   Mango  Apple  Banana  Passion fruit  Grape
A      4      5       2              5     10
B      5      4       3              5     11
C      6      3       5              5     12
D      3      0       2              5     13
E      1      2       7              5     14

In [24]:
fruits3['Passion fruit']=[5,4,3,2,1]
fruits3

   Mango  Apple  Banana  Passion fruit  Grape
A      4      5       2              5     10
B      5      4       3              4     11
C      6      3       5              3     12
D      3      0       2              2     13
E      1      2       7              1     14